LONGITUDINAL_PLANNER_OFFICIAL = 0
LONGITUDINAL_PLANNER_EXPERIMENTAL = 1
LONGITUDINAL_PLANNER_TN = 2

# Compatibility aliases. Planner IDs are persistent and must not be renumbered.
LONGITUDINAL_PLANNER_DEFAULT = LONGITUDINAL_PLANNER_OFFICIAL
LONGITUDINAL_PLANNER_CRAZYMAX = LONGITUDINAL_PLANNER_EXPERIMENTAL
LONGITUDINAL_PLANNER_LOCAL = LONGITUDINAL_PLANNER_EXPERIMENTAL

LONGITUDINAL_PLANNER_LABELS = {
  LONGITUDINAL_PLANNER_OFFICIAL: "Official",
  LONGITUDINAL_PLANNER_EXPERIMENTAL: "Experimental",
  LONGITUDINAL_PLANNER_TN: "TN-NoDEC",
}


def get_longitudinal_planner_mode(params) -> int:
  try:
    mode = int(params.get("LongitudinalPlannerMode", return_default=True))
  except (TypeError, ValueError):
    mode = LONGITUDINAL_PLANNER_OFFICIAL
  return mode if mode in LONGITUDINAL_PLANNER_LABELS else LONGITUDINAL_PLANNER_OFFICIAL
