LONGITUDINAL_PLANNER_DEFAULT = 0
LONGITUDINAL_PLANNER_CRAZYMAX = 1
LONGITUDINAL_PLANNER_TN = 2

# Compatibility aliases. Planner IDs are persistent and must not be renumbered.
LONGITUDINAL_PLANNER_OFFICIAL = LONGITUDINAL_PLANNER_DEFAULT
LONGITUDINAL_PLANNER_LOCAL = LONGITUDINAL_PLANNER_CRAZYMAX

LONGITUDINAL_PLANNER_LABELS = {
  LONGITUDINAL_PLANNER_DEFAULT: "Default",
  LONGITUDINAL_PLANNER_CRAZYMAX: "CrazyMax",
  LONGITUDINAL_PLANNER_TN: "TN-NoDEC",
}


def get_longitudinal_planner_mode(params) -> int:
  try:
    mode = int(params.get("LongitudinalPlannerMode", return_default=True))
  except (TypeError, ValueError):
    mode = LONGITUDINAL_PLANNER_DEFAULT
  return mode if mode in LONGITUDINAL_PLANNER_LABELS else LONGITUDINAL_PLANNER_DEFAULT
